#pragma config(Sensor, dgtl1,  dataLine,       sensorTouch)
#pragma config(Sensor, dgtl2,  univStop,       sensorTouch)
#pragma config(Sensor, dgtl3,  startLimit,     sensorTouch)
#pragma config(Sensor, dgtl4,  endLimit,       sensorTouch)
#pragma config(Sensor, dgtl5,  resetBtn,       sensorTouch)
#pragma config(Motor,  port2,           light,         tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port3,           driveStart,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           driveEnd,      tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define FORWARDSPEED 25
#define RESETSPEED  -40

#include "conveyor_includes.c"
#include "e_stop.c"


task main()
{
	startTask(e_stop);
	int lastDLval = 0;
	int DLval = 0;
	int count = 0;
	while(true)
	{

		motor[light] = 0; // light off
		setConvSpeed(RESETSPEED);

		while(SensorValue[startLimit] == 0)
		{

			wait1Msec(10);
		}

		setConvSpeed(0);
		motor[light] = 127; // light on

		while(SensorValue[endLimit] != 1)
		{

			DLval = SensorValue[dataLine];
			//writeDebugStreamLine("%d", DLval);
			if(DLval && lastDLval != DLval) // rising edge detector
			{
				if(count == 0)
				{
					clearTimer(T1);
				}
				count = count + 1;
			}

			if(count != 0 && time1[T1] > 200)
			{
				interpretCount(count);
				count = 0;
			}

			lastDLval = DLval; // gets value of DL on last loop to compare to next loop
			wait1Msec(50); // do not remove, prevents rapid toggling of button value somehow.
		}

		setConvSpeed(0);
		while(SensorValue[resetBtn] == 0)
			wait1Msec(10);

	}

}
