#pragma config(Sensor, dgtl1,  dataLine,       sensorTouch)
#pragma config(Sensor, dgtl2,  univStop,       sensorTouch)
#pragma config(Sensor, dgtl3,  startLimit,     sensorTouch)
#pragma config(Sensor, dgtl4,  endLimit,       sensorTouch)
#pragma config(Sensor, dgtl5,  resetBtn,       sensorTouch)
#pragma config(Motor,  port1,           light,         tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port3,           driveStart,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           driveEnd,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define FORWARDSPEED 50
#define RESETSPEED  -50

#include "conveyor_includes.c"
#include "e_stop.c"


task main()
{
	startTask(e_stop);
	bool last_DL_val, DL_val = false;
	int count = 0;

	while(true)
	{

		motor[light] = 0; // light off
		setConvSpeed(RESETSPEED);

		while(SensorValue[startLimit] == 0)
		{

			delay(10);
		}

		setConvSpeed(0);
		motor[light] = 127; // light on


		while(SensorValue[endLimit] == 0)
		{
			DL_val = (bool)SensorValue[dataLine];

			if(DL_val && DL_val != last_DL_val) // rising edge detector
			{
				if(count == 0)
					clearTimer(T1);

				count++;

			}

			if(count != 0 && time1[T1] > 100)
			{
				interpretCount(count);
				count = 0;
			}

			last_DL_val = DL_val; // gets value of DL on last loop to compare to next loop
		}

		setConvSpeed(0);
		while(SensorValue[resetBtn] == 0)
			delay(10);
	}

}
