#pragma config(Sensor, dgtl1,  convComm,       sensorDigitalOut)
#pragma config(Sensor, dgtl2,  univStop,       sensorDigitalIn)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

