#pragma config(Sensor, in1,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  convComm,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  univStop,       sensorTouch)
#pragma config(Motor,  port4,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*											Template for Automation Project											 */
/*---------------------------------------------------------------------------*/

#include "template_includes.c" // includes main portion of background code.

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                          Pre-Operate Functions                            */
/*                                                                           */
/*  You may want to perform some actions as soon as the bot turns on.  			 */
/*  Do them in the following function. You must return from this function    */
/*  or the operate function will not be started.                             */
/*---------------------------------------------------------------------------*/

void init()
{
	// change iLightSensorMax if you find the value of the light sensor that begins operate()
	// is too sensitive or not sensitive enough.
	iLightSensorMax = 60;

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This function is used to control your robot when light from the          */
/*  conveyor is detected.     																							 */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*  make sure to use startConv and stopConv to move the conveyor             */
/*	unless you don't need it. If needed you can call them multiple times in  */
/*	the code.                                                                */
/*---------------------------------------------------------------------------*/

void operate()
{

	wait1Msec(250);
	stopConv(); // use whenever you want, this is just the minimum requirements for conv robots
	motor[claw] = 40;
	wait1Msec(3000);
	motor[claw] = 0;
	startConv(); // make sure this statement is used when the parsing has finished.
}
